"""add report_language to app_settings

Revision ID: 3fdafcee75ab
Revises: cf13197306e5
Create Date: 2025-12-22 21:23:31.038173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdafcee75ab'
down_revision = 'cf13197306e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_language', sa.String(length=5), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('report_language')

    # ### end Alembic commands ###
