"""No-op: partial index using CURRENT_DATE is invalid on PostgreSQL.
Ensure plain index on expiry_date exists instead.
"""
from alembic import op

# Generated by Alembic
revision = "b4e7b9d54aa6"
down_revision = "31eaf7771755"
branch_labels = None
depends_on = None

def upgrade():
    # نضمن فقط وجود الفهرس العادي (آمن مع IF NOT EXISTS)
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_lots_expiry_date
        ON lots (expiry_date);
    """)

def downgrade():
    # ما نحذف والو (الفهرس العادي راه ممكن يكون من قبل)
    pass
