"""Full sync with current models

Revision ID: c0c16cc7fec9
Revises: b4e7b9d54aa6
Create Date: 2025-10-17 23:26:34.796020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c16cc7fec9'
down_revision = 'b4e7b9d54aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.alter_column('lot_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('pn',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_column('thumb')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumb', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('pn',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('product_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('lot_number',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
