"""add constraints to app_settings

Revision ID: e1bfba6fa95e
Revises: eeb915a5ee93
Create Date: 2025-12-15 09:43:02.369172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bfba6fa95e'
down_revision = 'eeb915a5ee93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('export_day',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('last_export_error')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_export_error', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('export_day',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
