"""Add AppSettings table

Revision ID: eeb915a5ee93
Revises: c0c16cc7fec9
Create Date: 2025-12-14 21:13:02.639858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb915a5ee93'
down_revision = 'c0c16cc7fec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quality_email', sa.String(length=255), nullable=True),
    sa.Column('auto_export_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.alter_column('lot_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('pn',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.alter_column('pn',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('lot_number',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.drop_table('app_settings')
    # ### end Alembic commands ###
